server:
  port:
    8888

spring:
  datasource:
      username: admin
      password: VgCaMPwB1PEoeU+aQuHB2kj0A8CXlM06MFrHaQwXFD/NbSjxdryF+OB0zvzaFDGPAQ2Uq3l3sBEuzURJk47nlA==
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://116.196.94.167:3306/Y_club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
        initial-size: 20
        min-idle: 20
        max-active: 100
        max-wait: 60000
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          login-username: admin
          login-password: VgCaMPwB1PEoeU+aQuHB2kj0A8CXlM06MFrHaQwXFD/NbSjxdryF+OB0zvzaFDGPAQ2Uq3l3sBEuzURJk47nlA==
        filter:
          stat:
            enabled: true
            slow-sql-mills: 2000
            log-slow-sql: true
          wall:
            enabled: true
          config:
            enabled: true

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALhpARMW0oJmyblpviRSn3tmZ/FInl4GzvQ8K1MX8y0eN7Is8Cfd2GBo5DgbBVPb4lD7z+Famv5Vde4MxsOw5RsCAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml
